import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

const api_url = "https://dreams.hashref.org/api/";

const String baseURL = api_url;
const String login = baseURL + "login";
const String register = baseURL + "register";
const String change_pswd = baseURL + "change-password";
const String faq = baseURL + "faq";
const String category = baseURL + "category";
const String course = baseURL + "course";
const String teacher = baseURL + "teacher";
const String exam = baseURL + "competitive-exam-type";
const String terms = baseURL + "terms";
const String about = baseURL + "about";
const String freesession = baseURL + "freesession";
const String enquiry = baseURL + "enquiry";
const String feedback = baseURL + "feedback";
const String course_page = baseURL + "course-page";
const String topic = baseURL + "topic";
const String resource_video = baseURL + "resource-video";
const String resource_pdf = baseURL + "resource-pdf";
const String state = baseURL + "state";
const String mycourse = baseURL + "booking-data";
const String pdf = baseURL + "pdf";
const String click_cart = baseURL + "add-to-cart";
const String add_cart = baseURL + "cart";
const String delete_cart = baseURL + "cart-delete";
const String cart_price = baseURL + "cart-total";
const String course_topics = baseURL + "course-topics";
const String course_details = baseURL + "course-details";
const String banner = baseURL + "banner";
const String schedule_link = baseURL + "schedules";
const String mybooking = baseURL + "booking-data";
const String exam_details = baseURL + "competitive-exam-details";
