// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz55KNM3OFo2du3eHGclge1dZXcuCZ5qc',
    appId: '1:241555539294:web:3135a3a56d6cca88e33bcf',
    messagingSenderId: '241555539294',
    projectId: 'childrensmedha',
    authDomain: 'childrensmedha.firebaseapp.com',
    storageBucket: 'childrensmedha.appspot.com',
    measurementId: 'G-ZV4JG918BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdS2e2T0ZuTFzrGJvt5mtsS2Y7KG4Iphw',
    appId: '1:241555539294:android:a38c9b32d6d2eed1e33bcf',
    messagingSenderId: '241555539294',
    projectId: 'childrensmedha',
    storageBucket: 'childrensmedha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtECAn-Ocyr2ElPtQzsO0Lmxa5TozHkwA',
    appId: '1:241555539294:ios:3307087e34ff9bfde33bcf',
    messagingSenderId: '241555539294',
    projectId: 'childrensmedha',
    storageBucket: 'childrensmedha.appspot.com',
    iosBundleId: 'com.example.cmedha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtECAn-Ocyr2ElPtQzsO0Lmxa5TozHkwA',
    appId: '1:241555539294:ios:2e06cf74b9f93868e33bcf',
    messagingSenderId: '241555539294',
    projectId: 'childrensmedha',
    storageBucket: 'childrensmedha.appspot.com',
    iosBundleId: 'com.example.cmedha.RunnerTests',
  );
}
